name: Latest blog post

on:
  schedule:
    - cron: '0 14 */2 * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://felixisaac.dev/blog/feed"
